name: CI

on:
  pull_request:
    types: [ labeled ]

jobs:
  build:
    environment: test_go
    if: ${{ github.event.label.name == 'Build' }}
    runs-on: ubuntu-latest
    
    steps:
      # - uses: actions/checkout@v2
      # - name: Run a one-line script
      #   run: echo ${{ secrets.DOCKERHUB_USERNAME }}, ${{ secrets.DOCKERHUB_TOKEN }}, $secrets.DOCKERHUB_USERNAME, $secrets.DOCKERHUB_TOKEN
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest
